apiVersion: apps/v1
kind: Deployment
metadata:
  name: school-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: school-app
  template:
    metadata:
      labels:
        app: school-app
    spec:
      containers:
      - name: school-app
        image: us-central1-docker.pkg.dev/velvety-maker-480912-u3/school-app-repo/school-app:9
        ports:
        - containerPort: 5000
